apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: grafana-data
    namespace: grafana
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 20Gi
kind: List
